In [25]:
import gpytorch
import numpy as np
import torch

In [3]:
k0 = gpytorch.kernels.RQKernel(alpha=0.1)

In [5]:
k0.alpha

tensor([0.6931], grad_fn=<SoftplusBackward>)

In [6]:
k0.raw_alpha

Parameter containing:
tensor([0.], requires_grad=True)

In [7]:
k0.alpha = 0.1

In [8]:
k0.alpha

tensor([0.1000], grad_fn=<SoftplusBackward>)

In [11]:
k1 = gpytorch.kernels.RQKernel()

In [10]:
alphas = [0.1, 1, 10]

In [14]:
k0 + k1

AdditiveKernel(
  (kernels): ModuleList(
    (0): RQKernel(
      (raw_lengthscale_constraint): Positive()
      (raw_alpha_constraint): Positive()
    )
    (1): RQKernel(
      (raw_lengthscale_constraint): Positive()
      (raw_alpha_constraint): Positive()
    )
  )
)

In [ ]:
rq_kernels = []
for alpha in alpha:
    k = gpytorch.kernels.RQKernel()
    k.alpha = alpha
    rq_kernels.append(k)
kernel = 

In [29]:
linear_kernel = gpytorch.kernels.LinearKernel()

In [32]:
linear_kernel.variance = 1.

In [33]:
linear_kernel(torch.tensor([1, 2]), torch.tensor([1, 1])).evaluate()

tensor([[1., 1.],
        [2., 2.]], grad_fn=<MmBackward>)

In [34]:
linear_kernel = gpytorch.kernels.LinearKernel()
linear_kernel.variance = 1.
kernel = linear_kernel
for alpha in alphas:
    rq_kernel = gpytorch.kernels.RQKernel()
    rq_kernel.alpha = alpha
    kernel += rq_kernel

In [36]:
rq01 = gpytorch.kernels.RQKernel()
rq01.alpha = 0.1
rq1 = gpytorch.kernels.RQKernel()
rq1.alpha = 1
rq10 = gpytorch.kernels.RQKernel()
rq10.alpha = 10
lin = gpytorch.kernels.LinearKernel()
linear_kernel.variance = 1.

In [37]:
kernel = rq01 + rq1 + rq10 + lin

In [38]:
kernel

AdditiveKernel(
  (kernels): ModuleList(
    (0): AdditiveKernel(
      (kernels): ModuleList(
        (0): AdditiveKernel(
          (kernels): ModuleList(
            (0): RQKernel(
              (raw_lengthscale_constraint): Positive()
              (raw_alpha_constraint): Positive()
            )
            (1): RQKernel(
              (raw_lengthscale_constraint): Positive()
              (raw_alpha_constraint): Positive()
            )
          )
        )
        (1): RQKernel(
          (raw_lengthscale_constraint): Positive()
          (raw_alpha_constraint): Positive()
        )
      )
    )
    (1): LinearKernel(
      (raw_variance_constraint): Positive()
    )
  )
)

In [41]:
kernel(torch.tensor([1, 2]), torch.tensor([1, 5])).evaluate()

tensor([[3.6931, 4.1217],
        [3.0318, 7.6637]], grad_fn=<AddBackward0>)